# workflow의 이름
name: CI/CD

# 해당 workflow가 언제 실행될 것인지에 대한 트리거를 지정
on:
  push:
    branches: [ develop ] # develop branch로 push 될 때 실행됩니다.

# 해당 yml 내에서 사용할 key - value
env:
  S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  PROJECT_NAME: ${{ secrets.AWS_CODEDEPLOY_PROJECT_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_CODEDEPLOY_APPLICATION_NAME: ${{ secrets.AWS_CODEDEPLOY_APPLICATION_NAME }}
  AWS_CODEDEPLOY_GROUP_NAME: ${{ secrets.AWS_CODEDEPLOY_GROUP_NAME }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_SG_ID: ${{ secrets.AWS_SG }}

# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있습니다.
jobs:
  build:
    name: CI
    # 해당 jobs에서 아래의 steps들이 어떠한 환경에서 실행될 것인지를 지정합니다.
    runs-on: ubuntu-latest

    steps:
      # 작업에서 액세스할 수 있도록 $GITHUB_WORKSPACE에서 저장소를 체크아웃합니다.
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Get Github action IP # 액션 IP 얻어오기
        id: ip
        uses: haythem/public-ip@v1.2
        continue-on-error: true

      - name: Get Public IP if previous step failed
        if: failure()
        run: |
          public_ip=$(curl -s ifconfig.me)
          echo "PUBLIC_IP=${public_ip}" >> $GITHUB_ENV

      - name: Setting environment variables # 환경변수 설정
        run: |
          echo "AWS_DEFAULT_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_SG_NAME=launch-wizard-2" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Add Github Actions IP to Security group
        run: | # 명령어로 시큐리티 그룹 인바운드 임시 설정
          ip_address="${{ steps.ip.outputs.ipv4 }}"
          if [ -z "$ip_address" ]; then
            ip_address="${{ env.PUBLIC_IP }}"
          fi
          aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 3306 --cidr ${ip_address}/32 

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle 
        run: ./gradlew build
        shell: bash

      - name: Remove Github Actions IP from security group
        run: | # 작업이 끝났으니 다시 인바운드 룰에서 제거
          ip_address="${{ steps.ip.outputs.ipv4 }}"
          if [ -z "$ip_address" ]; then
            ip_address="${{ env.PUBLIC_IP }}"
          fi
          aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 3306 --cidr ${ip_address}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

  deploy:
    name: CD
    needs: build
    # 해당 jobs에서 아래의 steps들이 어떠한 환경에서 실행될 것인지를 지정합니다.
    runs-on: ubuntu-latest

    steps:
      # 작업에서 액세스할 수 있도록 $GITHUB_WORKSPACE에서 저장소를 체크아웃합니다.
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Get Github action IP # 액션 IP 얻어오기
        id: ip
        uses: haythem/public-ip@v1.2
        continue-on-error: true

      - name: Get Public IP if previous step failed
        if: failure()
        run: |
          public_ip=$(curl -s ifconfig.me)
          echo "PUBLIC_IP=${public_ip}" >> $GITHUB_ENV

      - name: Setting environment variables # 환경변수 설정
        run: |
          echo "AWS_DEFAULT_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_SG_NAME=launch-wizard-2" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Add Github Actions IP to Security group
        run: | # 명령어로 시큐리티 그룹 인바운드 임시 설정
          ip_address="${{ steps.ip.outputs.ipv4 }}"
          if [ -z "$ip_address" ]; then
            ip_address="${{ env.PUBLIC_IP }}"
          fi
          aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 3306 --cidr ${ip_address}/32
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Remove Github Actions IP from security group
        run: | # 작업이 끝났으니 다시 인바운드 룰에서 제거
          ip_address="${{ steps.ip.outputs.ipv4 }}"
          if [ -z "$ip_address" ]; then
            ip_address="${{ env.PUBLIC_IP }}"
          fi
          aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 3306 --cidr ${ip_address}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      # S3에 업로드
      - name: Upload to S3
        run: aws s3 cp --region $AWS_REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      # Deploy
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name $AWS_CODEDEPLOY_APPLICATION_NAME \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name $AWS_CODEDEPLOY_GROUP_NAME \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip \
          --region $AWS_REGION \
